# GP CODES 


In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
points = np.array([[1, 2, 3,1, 2, 3],
                   [4, 5, 6, 4, 5, 6],
                   [1, 1, 2, 1, 1, 2],
                   [2, 2, 8, 2, 2, 8],
                   [5, 7, 12,5, 7, 12],
                   [12, 15, 7,12, 15, 7],
                   [8, 10, 4,8, 10, 4] ])

print(points)


[[ 1  2  3  1  2  3]
 [ 4  5  6  4  5  6]
 [ 1  1  2  1  1  2]
 [ 2  2  8  2  2  8]
 [ 5  7 12  5  7 12]
 [12 15  7 12 15  7]
 [ 8 10  4  8 10  4]]


In [3]:

encoder = keras.models.Sequential([keras.layers.Dense(4, input_shape=[6]),
                                   keras.layers.Dense(2, input_shape=[4])])

decoder = keras.models.Sequential([keras.layers.Dense(4, input_shape=[2]),
                                   keras.layers.Dense(6, input_shape=[4])])

In [4]:
ae = keras.models.Sequential([encoder, decoder])
ae.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=0.001))

X_train = points

In [ ]:
history = ae.fit(X_train, X_train, epochs=5000)
codings = encoder.predict(X_train)
print(codings)

Train on 7 samples
Epoch 1/5000
